### PR TITLE
Add arcana.elfscan source and blog post

### PR DESCRIPTION
**Pull request by v-rzh**
Add elfmaster's blog and source code for `arcana.elfscan`.

### CODE REVIEW

**Review by sblip2 — COMMENTED** [review]
Approved

**Comment by v-rzh** [comment]
I still can't merge this.

**Review by sblip2 — APPROVED** [review]

**Comment by sblip2** [comment]
> I still can't merge this.

What does it say?

**Review by sblip2 — COMMENTED** [review]
reviewed

**Comment by v-rzh** [comment]
I just didn't have the privs to merge I guess. All good :)

**Pull request merged**
